# Generated by Django 5.2.8 on 2025-11-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compete',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
